--DROP TABLE IF EXISTS noakweather.silver_observations;

CREATE EXTERNAL TABLE IF NOT EXISTS noakweather.silver_observations (
    observation_id STRING COMMENT 'Unique observation ID',
    observation_type STRING COMMENT 'METAR, TAF, SYNOP, etc.',
    station_id STRING COMMENT 'ICAO or WMO station identifier',
    observation_time TIMESTAMP COMMENT 'Observation timestamp (UTC)',
    ingestion_time TIMESTAMP COMMENT 'When ingested into Bronze layer',
    processing_time TIMESTAMP COMMENT 'When transformed to Silver layer',
    latitude DOUBLE COMMENT 'Station latitude (decimal degrees)',
    longitude DOUBLE COMMENT 'Station longitude (decimal degrees)',
    elevation_meters INT COMMENT 'Station elevation (meters)',
    temperature_celsius DOUBLE COMMENT 'Air temperature',
    dewpoint_celsius DOUBLE COMMENT 'Dewpoint temperature',
    temperature_spread_celsius DOUBLE COMMENT 'Temperature-dewpoint spread',
    relative_humidity_percent DOUBLE COMMENT 'Relative humidity (0-100)',
    heat_index_celsius DOUBLE COMMENT 'Heat index',
    wind_direction_degrees INT COMMENT 'Wind direction (0-360)',
    wind_speed_knots INT COMMENT 'Wind speed',
    wind_gust_knots INT COMMENT 'Wind gust speed',
    wind_cardinal_direction STRING COMMENT 'Cardinal direction (N, NE, E, etc.)',
    is_wind_calm BOOLEAN COMMENT 'Calm winds',
    is_wind_variable BOOLEAN COMMENT 'Variable wind direction',
    visibility_meters DOUBLE COMMENT 'Prevailing visibility',
    is_visibility_less_than BOOLEAN COMMENT 'Visibility is less than reported value',
    is_cavok BOOLEAN COMMENT 'Ceiling and visibility OK',
    pressure_hpa DOUBLE COMMENT 'Altimeter setting',
    pressure_altitude_feet DOUBLE COMMENT 'Pressure altitude',
    sea_level_pressure_hpa DOUBLE COMMENT 'Sea level pressure (from remarks)',
    ceiling_feet INT COMMENT 'Ceiling height',
    ceiling_meters INT COMMENT 'Ceiling height (meters)',
    lowest_cloud_base_feet INT COMMENT 'Lowest cloud layer base',
    sky_coverage STRING COMMENT 'Overall sky coverage (CLR, FEW, SCT, BKN, OVC)',
    has_cumulonimbus BOOLEAN COMMENT 'Cumulonimbus present',
    has_towering_cumulus BOOLEAN COMMENT 'Towering cumulus present',
    present_weather STRING COMMENT 'Current weather (codes)',
    weather_intensity STRING COMMENT 'Intensity (light, moderate, heavy)',
    has_thunderstorm BOOLEAN COMMENT 'Thunderstorm in vicinity or at station',
    has_precipitation BOOLEAN COMMENT 'Any precipitation occurring',
    has_fog BOOLEAN COMMENT 'Fog or mist present',
    flight_category STRING COMMENT 'VFR, MVFR, IFR, LIFR',
    is_vfr BOOLEAN COMMENT 'Visual flight rules conditions',
    is_ifr BOOLEAN COMMENT 'Instrument flight rules conditions',
    is_marginal_vfr BOOLEAN COMMENT 'Marginal VFR conditions',
    is_low_ifr BOOLEAN COMMENT 'Low IFR conditions',
    rvr_runway_id STRING COMMENT 'RVR runway identifier',
    rvr_visual_range_feet INT COMMENT 'RVR visibility',
    rvr_variable_low_feet INT COMMENT 'RVR variable low',
    rvr_variable_high_feet INT COMMENT 'RVR variable high',
    raw_text STRING COMMENT 'Original observation text',
    unparsed_tokens STRING COMMENT 'Tokens not recognized by parser',
    processor_version STRING COMMENT 'Parser/processor version',
    is_automated BOOLEAN COMMENT 'Automated station',
    automated_station_type STRING COMMENT 'Type of automation',
    quality_score DOUBLE COMMENT 'Overall quality score (0-100)',
    completeness_score DOUBLE COMMENT 'Data completeness (0-100)',
    has_temperature BOOLEAN COMMENT 'Temperature field present',
    has_wind BOOLEAN COMMENT 'Wind field present',
    has_pressure BOOLEAN COMMENT 'Pressure field present',
    has_visibility BOOLEAN COMMENT 'Visibility field present',
    validation_flags STRING COMMENT 'Validation issues (comma-separated)',
    observation_summary STRING COMMENT 'Human-readable summary'
)
COMMENT 'Silver: Standardized weather observations (all sources, validated, Parquet)'
PARTITIONED BY (
    data_source STRING COMMENT 'Source system (NOAA, OpenWeatherMap, etc.)',
    year STRING,
    month STRING,
    day STRING
)
STORED AS PARQUET
LOCATION 's3://noakweather-data/silver/observations/'
TBLPROPERTIES (
    'parquet.compression'='SNAPPY',
    'projection.enabled'='true',
    'projection.data_source.type'='enum',
    'projection.data_source.values'='noaa,openweathermap,weatherapi',
    'projection.year.type'='integer',
    'projection.year.range'='2020,2030',
    'projection.year.digits'='4',
    'projection.month.type'='integer',
    'projection.month.range'='01,12',
    'projection.month.digits'='2',
    'projection.day.type'='integer',
    'projection.day.range'='01,31',
    'projection.day.digits'='2',
    'storage.location.template'='s3://noakweather-data/silver/observations/${data_source}/${year}/${month}/${day}'
);
